[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "aiogram>=3.18.0",
    "aiohttp>=3.11.12",
    "discord-py>=2.5.2",
    "flask>=3.1.1",
    "twilio>=9.4.6",
]
